### ISSUE TITLE
How to change the number of clients, the "num_clients" parameter does not work？

### ISSUE THREAD

**Issue by niecf** [lishenghui/blades#22]
Hello, your code helped me a lot, but I found a problem during my use: how to change the total number of clients. I set both the "num_clients" parameter when generating the dataset and specifying "num_clients" in "aggregator_kws" (I'm using krum), but they don't work, there are always only 10 clients. Please how can I solve this problem, thanks.

**Comment by niecf** [comment]
Below is my configuration：

mnist = MNIST(data_root="./data", train_bs=32, num_clients=100)  # built-in federated MNIST dataset

# configuration parameters
conf_params = {
    "dataset": mnist,
    "aggregator": "krum",  # aggregation
    "aggregator_kws": {"num_clients": 100,  # attacker parameters
                  "num_byzantine": 10},
    "num_byzantine": 10,  # number of Byzantine input
    "attack": "noise",  # attack strategy
    # "attack_kws": {"num_clients": 100,  # attacker parameters
    #                  "num_byzantine": 10},
    "num_actors": 4,  # number of training actors
    # "num_actors": 10,  # number of training actors
    "use_cuda": False,
    "gpu_per_actor": 0.,
    "seed": 1,  # reproducibility
}

**Comment by lishenghui** [comment]
Hi, this is because the dataset is dumped into a file to avoid unnecessary reconstruction. The code immediately loads the cache file if it exists. But we forgot to compare the detailed information with the new configuration. We will fix this issue soon. 

So far, there is a quick solution to make it work: you can remove the "MNIST.obj" files in the data_root folder so that the dataset will be separated into your desired number of partitions.

**Comment by niecf** [comment]
Thank you for your answer.
