### ISSUE TITLE
Outdated Examples

### ISSUE THREAD

**Issue by castortroy05** [lishenghui/blades#62]
I'm not sure if you're aware, or if this situation only exists on the multiple OS's I have run the simulation suite on, but the example files you have and even the main code, simply do not work.

There are many references which may be python version specific, as they simply prevent the program from running at all,
for example, to import the simulator, you constantly refer to blades.core.simulator, however this only works when it's called as blades.simulator not .core. 
![image](https://user-images.githubusercontent.com/44813655/204024666-55d59c7c-5a03-4d33-8794-39e10ac26081.png)

The import of options from args does not work, and appears to be a python2 file.
![image](https://user-images.githubusercontent.com/44813655/204024558-21516b61-3f80-43bf-9028-49cf93d01a9a.png)

I have created brand new environments including only the files needed for this project and the problems remain. I have also tried this on various python 3 platforms, in windows and linux, and each time I am unable to have things operate in the methods you have identified.

I was desperate to use this suite as it fit the needs of my research paper, but my lack of ability to operate it, made this a frustrating exercise.

**Comment by yosen-king** [comment]
I also struggle with that, may be the code is not complete. Hope to finish it perfectly.

**Comment by lishenghui** [comment]
Hi, I apologize for the inconvenience caused. Yes, the examples are seriously outdated due to the change in APIs, and I have deprecated them for now. At the moment, it is strongly recommended to run the code with [Developer mode](https://github.com/bladesteam/blades#installation), which works well according to my test. You may have to look into the source code to make any modifications. 

I plan to release a new version of the simulation suit, as well as the examples, in next month, which will have a more efficient backend and more friendly APIs. Please stay tuned!

**Comment by yosen-king** [comment]
> 

Nice work, I look forward to using blades.
